apiVersion: etcd.uisee.com/v1alpha1
kind: EtcdCluster
metadata:
  labels:
    app.kubernetes.io/name: etcdcluster
    app.kubernetes.io/instance: etcdcluster-sample
    app.kubernetes.io/part-of: etcd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: etcd-operator
  name: etcdcluster-sample
spec:
  size: 3
  image: wangshaojun11/etcd:v3.4.13
  storageclass: abc
  storagesize: 1Gi
